name: Build & Deploy to ECS

on:
  workflow_dispatch:      # Elle tetikleme
  push:
    branches: [ main ]   # main'e push olduÄŸunda Ã§alÄ±ÅŸÄ±r

env:
  PROJECT_NAME: testinium-logo-service-7wxnl689
  AWS_REGION: us-west-2
  ECS_CLUSTER: testinium-cluster
  PUBLIC_ECR_URI: public.ecr.aws/h7j5l7r8/testinium

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    # ðŸ”‘ OIDC iÃ§in gerekli izinler
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::737062070137:role/github-odic
          aws-region: ${{ env.AWS_REGION }}

      - name: Who am I? (debug)
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Get short SHA
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build & Push Docker image to Public ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.PUBLIC_ECR_URI }}:${{ steps.sha_short.outputs.sha_short }}
            ${{ env.PUBLIC_ECR_URI }}:latest

      - name: Restart ECS service (pull latest)
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.PROJECT_NAME }} \
            --region ${{ env.AWS_REGION }} \
            --force-new-deployment
