name: Docker build job

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: testinium-logo-service-7wxnl689
  AWS_REGION: us-west-1
  ECS_CLUSTER: testinium-cluster
  PUBLIC_ECR_URI: public.ecr.aws/h7j5l7r8/testinium

jobs:
  buildDockerImage:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # OIDC iÃ§in
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set short sha
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::737062070137:role/odic-deneme
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Build & Push Docker image to Public ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.PUBLIC_ECR_URI }}:${{ steps.sha_short.outputs.sha_short }}
            ${{ env.PUBLIC_ECR_URI }}:latest

      - name: Restart ECS service (pull latest)
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.PROJECT_NAME }}-service \
            --region ${{ env.AWS_REGION }} \
            --force-new-deployment
