name: Connect to an AWS role from a GitHub repository

# İş akışının tetikleneceği durumlar
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-west-2   # Kaynaklarınızın bulunduğu AWS Bölgesi

# İş akışı ve job seviyesinde izinler
permissions:
  id-token: write   # OIDC için gerekli
  contents: read    # actions/checkout için gerekli

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      # Repo kodunu çek
      - name: Git clone the repository
        uses: actions/checkout@v3

      # AWS rolünü üstlen ve credentials ayarla
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::737062070137:role/odic-deneme
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      # AWS CLI ile kimlik doğrulama testi
      - name: STS GetCallerIdentity
        run: |
          aws sts get-caller-identity
